# Generated by Django 5.1.1 on 2024-11-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CustomerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SellerProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='recruiterProfileModel',
        ),
        migrations.DeleteModel(
            name='seekerProfileModel',
        ),
    ]
