# Generated by Django 5.1.1 on 2024-11-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_caloriecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriecounter',
            name='cartItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.cartitem'),
        ),
    ]
