# Generated by Django 5.1.1 on 2024-11-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_caloriecounter_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caloriecounter',
            name='cartItem',
        ),
        migrations.AddField(
            model_name='caloriecounter',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
