# Generated by Django 5.1.1 on 2024-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_remove_caloriecounter_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
    ]
