# Generated by Django 5.1.1 on 2024-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_customuser_activity_level_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivered',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('cancel', 'Cancel')], default='pending', max_length=50, null=True),
        ),
    ]
